import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import styled from 'styled-components';
import Link from 'next/link';

const StyledBackground = styled.div`
background: linear-gradient(to right, #8e9eab 0%, #eef2f3  51%, #8e9eab  100%);
`

const StyledButton = styled.button`
 font-size:24px;
 font-weight:500;
 display: flex;
 align-items:center;
 justify-content:center;
 width:250px;


  background: linear-gradient(to right, #FF512F 0%, #F09819  51%, #FF512F  100%);

            margin: 10px;
            padding: 25px 60px;
            text-align: center;
            text-transform: uppercase;
            transition: 0.5s;
            background-size: 200% auto;
            color: white;            
            box-shadow: 0 0 20px #eee;
            border-radius: 10px;
          
          &:hover {
            background-position: right center; 
            color: #fff;
            text-decoration: none;
          }
        
         
`;

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <StyledBackground className="flex flex-col  items-center h-screen justify-center">
            <div className="md:grid md:grid-cols-2 gap-40">
            <Link href='/employees' passhref>
                    <StyledButton>
                      <p>Employees</p>
                    </StyledButton>
            </Link>
    
                    <StyledButton>
                      <p>Clients</p>
                    </StyledButton>
            
            </div>
            <div className="md:grid md:grid-cols-2 gap-40 mt-20">
            
                    <StyledButton>
                      <p>Candidates</p>
                    </StyledButton>
            
            
                    <StyledButton>
                      <p>Clients</p>
                    </StyledButton>
            
            </div>
        </StyledBackground>
      </div>
</>
  )
}
